package com.orangehrm.tests;

import com.github.javafaker.Faker;
import com.orangehrm.pages.AddEmployeePage;
import com.orangehrm.pages.DashboardPage;
import com.orangehrm.pages.EmployeeListPage;
import org.testng.Assert;
import org.testng.annotations.Test;

/**
 * EmployeeTests - Test suite for OrangeHRM PIM / Employee module.
 * Covers: employee list, add employee, search, validation.
 */
public class EmployeeTests extends BaseTest {

    private static final Faker faker = new Faker();

    // ─── TC_EMP_001 ──────────────────────────────────────────────────────────

    @Test(priority = 1,
          description = "Verify Employee List page loads correctly")
    public void tc_emp_001_employeeListPageLoads() {
        logStep("TC_EMP_001: Verify Employee List page loads");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();

        Assert.assertTrue(employeeList.isPageDisplayed(),
            "Employee List page should be displayed");
        Assert.assertTrue(com.orangehrm.utils.DriverManager.getDriver()
            .getCurrentUrl().contains("viewEmployeeList"),
            "URL should contain 'viewEmployeeList'");
        logStep("PASS: Employee List page loaded successfully");
    }

    // ─── TC_EMP_002 ──────────────────────────────────────────────────────────

    @Test(priority = 2,
          description = "Verify Add Employee page loads when clicking Add button")
    public void tc_emp_002_addEmployeePageLoads() {
        logStep("TC_EMP_002: Verify Add Employee page navigation");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();
        AddEmployeePage addPage = employeeList.clickAddEmployee();

        Assert.assertTrue(addPage.isPageDisplayed(),
            "Add Employee page should be displayed");
        Assert.assertTrue(com.orangehrm.utils.DriverManager.getDriver()
            .getCurrentUrl().contains("addEmployee"),
            "URL should contain 'addEmployee'");
        logStep("PASS: Add Employee page displayed correctly");
    }

    // ─── TC_EMP_003 ──────────────────────────────────────────────────────────

    @Test(priority = 3,
          description = "Verify adding a new employee with first name and last name only")
    public void tc_emp_003_addNewEmployeeMinimalData() {
        logStep("TC_EMP_003: Add new employee with minimal required data");

        String firstName = faker.name().firstName();
        String lastName  = faker.name().lastName();

        logStep("Adding employee: " + firstName + " " + lastName);

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();
        AddEmployeePage addPage = employeeList.clickAddEmployee();

        String autoEmpId = addPage.getAutoGeneratedEmployeeId();
        logStep("Auto-generated Employee ID: " + autoEmpId);

        addPage.enterFirstName(firstName)
               .enterLastName(lastName)
               .clickSave();

        // After save, should redirect to Employee List or Personal Details
        String currentUrl = com.orangehrm.utils.DriverManager.getDriver().getCurrentUrl();
        Assert.assertTrue(currentUrl.contains("pim"),
            "After save, URL should still be in PIM module");
        logStep("PASS: Employee added. Redirected to: " + currentUrl);
    }

    // ─── TC_EMP_004 ──────────────────────────────────────────────────────────

    @Test(priority = 4,
          description = "Verify Employee ID is auto-generated on Add Employee page")
    public void tc_emp_004_employeeIdAutoGenerated() {
        logStep("TC_EMP_004: Verify employee ID is auto-generated");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();
        AddEmployeePage addPage = employeeList.clickAddEmployee();

        String empId = addPage.getAutoGeneratedEmployeeId();

        Assert.assertNotNull(empId, "Employee ID should not be null");
        Assert.assertFalse(empId.isEmpty(), "Employee ID should not be empty");
        logStep("PASS: Auto-generated Employee ID: " + empId);
    }

    // ─── TC_EMP_005 ──────────────────────────────────────────────────────────

    @Test(priority = 5,
          description = "Verify search by first name returns results")
    public void tc_emp_005_searchByFirstName() {
        logStep("TC_EMP_005: Verify search by first name");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();

        employeeList.searchByFirstName("Admin")
                    .clickSearch();

        int rowCount = employeeList.getEmployeeTableRowCount();
        logStep("Records found for 'Admin': " + rowCount);

        Assert.assertTrue(rowCount >= 0,
            "Search should return results or no records message");
        logStep("PASS: Search by first name completed");
    }

    // ─── TC_EMP_006 ──────────────────────────────────────────────────────────

    @Test(priority = 6,
          description = "Verify search with invalid name shows no records")
    public void tc_emp_006_searchInvalidNameNoRecords() {
        logStep("TC_EMP_006: Verify search with non-existent name shows no records");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();

        employeeList.searchByFirstName("ZZZNOMATCH999XYZABC")
                    .clickSearch();

        Assert.assertTrue(employeeList.isNoRecordsFound()
            || employeeList.getEmployeeTableRowCount() == 0,
            "No records should be found for non-existent employee name");
        logStep("PASS: No records shown for invalid search term");
    }

    // ─── TC_EMP_007 ──────────────────────────────────────────────────────────

    @Test(priority = 7,
          description = "Verify Reset button clears search filters")
    public void tc_emp_007_resetClearsSearchFilters() {
        logStep("TC_EMP_007: Verify Reset button clears search filters");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();

        employeeList.searchByFirstName("TestEmployee")
                    .searchByLastName("TestSurname");

        employeeList.clickReset();

        // After reset, employee list should reload with all records
        int rowCount = employeeList.getEmployeeTableRowCount();
        logStep("Rows after reset: " + rowCount);

        Assert.assertTrue(rowCount >= 0,
            "After reset, table should display records");
        logStep("PASS: Reset button cleared search filters");
    }

    // ─── TC_EMP_008 ──────────────────────────────────────────────────────────

    @Test(priority = 8,
          description = "Verify Cancel button on Add Employee page returns to list")
    public void tc_emp_008_cancelAddEmployeeReturnsToList() {
        logStep("TC_EMP_008: Verify Cancel button on Add Employee page");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();
        AddEmployeePage addPage = employeeList.clickAddEmployee();

        addPage.enterFirstName("CancelTest")
               .enterLastName("User")
               .clickCancel();

        String currentUrl = com.orangehrm.utils.DriverManager.getDriver().getCurrentUrl();
        Assert.assertTrue(currentUrl.contains("pim"),
            "After cancel, should return to PIM module");
        logStep("PASS: Cancel returned to PIM module. URL: " + currentUrl);
    }

    // ─── TC_EMP_009 ──────────────────────────────────────────────────────────

    @Test(priority = 9,
          description = "Verify employee table is visible with at least one record")
    public void tc_emp_009_employeeTableHasRecords() {
        logStep("TC_EMP_009: Verify employee table contains records");

        DashboardPage dashboard = loginAsAdmin();
        EmployeeListPage employeeList = dashboard.navigateToPIM();

        int rowCount = employeeList.getEmployeeTableRowCount();
        logStep("Total employees found in table: " + rowCount);

        Assert.assertTrue(rowCount > 0,
            "Employee table should contain at least one record");
        logStep("PASS: Employee table has " + rowCount + " records");
    }
}
