package com.orangehrm.pages;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

/**
 * AddEmployeePage - PIM Module Add Employee Form.
 * URL: /web/index.php/pim/addEmployee
 */
public class AddEmployeePage extends BasePage {

    private static final Logger log = LogManager.getLogger(AddEmployeePage.class);

    // ─── Locators ─────────────────────────────────────────────────────────────

    @FindBy(xpath = "//h6[text()='Add Employee']")
    private WebElement pageHeader;

    @FindBy(xpath = "//input[@name='firstName']")
    private WebElement firstNameInput;

    @FindBy(xpath = "//input[@name='middleName']")
    private WebElement middleNameInput;

    @FindBy(xpath = "//input[@name='lastName']")
    private WebElement lastNameInput;

    @FindBy(xpath = "//input[@class='oxd-input oxd-input--active --field-error oxd-input--active' or @placeholder='Employee Id' or contains(@id,'employeeId')]")
    private WebElement employeeIdInput;

    @FindBy(xpath = "//label[text()='Employee Id']/../..//input")
    private WebElement employeeIdField;

    @FindBy(xpath = "//p[text()='Create Login Details']/..//input[@type='checkbox']")
    private WebElement createLoginDetailsToggle;

    @FindBy(xpath = "//input[@placeholder='Username']")
    private WebElement usernameInput;

    @FindBy(xpath = "//input[@type='password' and contains(@class,'oxd-input')]")
    private WebElement passwordInput;

    @FindBy(xpath = "(//input[@type='password' and contains(@class,'oxd-input')])[2]")
    private WebElement confirmPasswordInput;

    @FindBy(xpath = "//div[@class='oxd-radio-wrapper']//label[text()='Enabled']")
    private WebElement enabledStatusRadio;

    @FindBy(xpath = "//div[@class='oxd-radio-wrapper']//label[text()='Disabled']")
    private WebElement disabledStatusRadio;

    @FindBy(xpath = "//button[@type='submit']")
    private WebElement saveButton;

    @FindBy(xpath = "//button[@type='button' and text()=' Cancel ']")
    private WebElement cancelButton;

    @FindBy(xpath = "//span[contains(@class,'oxd-input-field-error-message')]")
    private WebElement requiredFieldError;

    // ─── Actions ──────────────────────────────────────────────────────────────

    public AddEmployeePage enterFirstName(String firstName) {
        log.info("Entering first name: {}", firstName);
        type(firstNameInput, firstName);
        return this;
    }

    public AddEmployeePage enterMiddleName(String middleName) {
        log.info("Entering middle name: {}", middleName);
        type(middleNameInput, middleName);
        return this;
    }

    public AddEmployeePage enterLastName(String lastName) {
        log.info("Entering last name: {}", lastName);
        type(lastNameInput, lastName);
        return this;
    }

    public String getAutoGeneratedEmployeeId() {
        return getAttributeValue(employeeIdField, "value");
    }

    public AddEmployeePage clearAndSetEmployeeId(String empId) {
        log.info("Setting employee ID: {}", empId);
        typeWithClear(employeeIdField, empId);
        return this;
    }

    public AddEmployeePage toggleCreateLoginDetails() {
        log.info("Toggling Create Login Details");
        jsClick(createLoginDetailsToggle);
        pause(500);
        return this;
    }

    public AddEmployeePage enterLoginUsername(String username) {
        log.info("Entering login username: {}", username);
        type(usernameInput, username);
        return this;
    }

    public AddEmployeePage enterLoginPassword(String password) {
        log.info("Entering login password");
        type(passwordInput, password);
        return this;
    }

    public AddEmployeePage confirmLoginPassword(String password) {
        log.info("Confirming login password");
        type(confirmPasswordInput, password);
        return this;
    }

    public EmployeeListPage clickSave() {
        log.info("Clicking Save button to add employee");
        click(saveButton);
        pause(2000);
        return new EmployeeListPage();
    }

    public EmployeeListPage clickCancel() {
        log.info("Clicking Cancel button");
        click(cancelButton);
        return new EmployeeListPage();
    }

    // ─── Assertions / Getters ─────────────────────────────────────────────────

    public boolean isPageDisplayed() {
        return isDisplayed(pageHeader);
    }

    public boolean isRequiredErrorDisplayed() {
        return isDisplayed(requiredFieldError);
    }

    public String getErrorMessage() {
        return getText(requiredFieldError);
    }
}
